feat(tests): set up framework for new tests
indeedeng/starfish pull request #48
Opened 2020-10-02 04:45 UTC by hackily

- Moves tests to its own folder
  - If test csv files are needed, they can be put into this folder.
- exports all helper functions from index.js so they can be imported into `tests.js`
- Add test setup and teardown for env variable
- Add tests for getOrThrow()

2020-10-05 18:54 UTC, danisyellis commented
Thanks for helping to flesh out our tests!
I'll be looking at/code reviewing/ merging in PRs later this week.

2020-10-07 18:53 UTC, danisyellis requested changes
These are some excellent additions to the project, thank you!
This will make it easier for people to add more tests. 
I've requested two small changes to your PR.

(BTW, I just wanted to let you know that eventually we'll be switching from chai to jest.)

2020-10-07 18:53 UTC, danisyellis commented on __tests__/test.js
> +const env = Object.assign({}, process.env);
Let's make this variable a bit more semantic - could you re-name it `envBeforeChanges` or something like that- to make it clearer what the intent of this code is?

2020-10-07 18:53 UTC, danisyellis commented on __tests__/test.js
> +    it('should return the value of a configuration that exists exists', () => {
small typo here - get rid of the extra `exists`

2020-10-08 07:47 UTC, hackily commented
> (BTW, I just wanted to let you know that eventually we'll be switching from chai to jest.)
Sounds like a great issue that someone can take up :)

2020-10-12 22:00 UTC, danisyellis approved these changes

2020-10-12 22:01 UTC, merged